# this docker compose is for quickly testing this plugin in a throwaway redmine service

services:
  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: redmine_root_pwd
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"  # Expose MariaDB port host
    # No host volume mapping for throwaway usage

  redmine:
    image: redmine:6.1
    ports:
      - "80:3000"  # expose on port 80 on host
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine
    volumes:
      # mount this repo inside the plugin directory
      - .:/usr/src/redmine/plugins/redmine_plugin_ci_test
      # No host volume mapping for throwaway usage
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:latest
    ports:
      - "443:443"  # HTTPS
    command: caddy reverse-proxy --from https://localhost:443 --to redmine:3000 --internal-certs
    depends_on:
      - redmine